/*
 * ethercat_setup.h
 *
 *  Created on: 14.02.2013
 *      Author: choll
 */

#ifndef ETHERCAT_SETUP_H_
#define ETHERCAT_SETUP_H_


#define NUM_SLAVES 1

//definitions for the bus connections and expected slave positions
#define SOMANET_0_Pos 0,0

//Vendor ID, Product Code  (see Output of ethercat cstruct)
#define SOMANET_ID 0x000022d2, 0x00000201

//Offsets
unsigned int somanet_0_o_offset=0;
unsigned int somanet_0_i_offset=0;


/*
 * Use the starting addresses for the digital I/O (see Output of ethercat -> pdo_entries[] )
 */
const static ec_pdo_entry_reg_t domain_regs[] = {
{SOMANET_0_Pos, SOMANET_ID, 0x7000, 1, &somanet_0_o_offset},
{SOMANET_0_Pos, SOMANET_ID, 0x6000, 1, &somanet_0_i_offset},
{}
};

//##################################################//
//#############Generated by:########################//
//#############ethercat slave#######################//
//#############(console##command)###################//
//##################################################//

/* Master 0, Slave 0, "Synapticon-ECAT"
 * Vendor ID:       0x000022d2
 * Product code:    0x00000201
 * Revision number: 0x0a000002
 */

ec_pdo_entry_info_t slave_0_pdo_entries[] = {
    {0x7000, 0x01, 16}, /* ECAT Out1 */
    {0x7000, 0x02, 16}, /* ECAT Out2 */
    {0x6000, 0x01, 16}, /* ECAT In1 */
    {0x6000, 0x02, 16}, /* ECAT In2 */
};

ec_pdo_info_t slave_0_pdos[] = {
    {0x1a00, 2, slave_0_pdo_entries + 0}, /* Outputs */
    {0x1600, 2, slave_0_pdo_entries + 2}, /* Inputs */
};

ec_sync_info_t slave_0_syncs[] = {
    {0, EC_DIR_OUTPUT, 0, NULL, EC_WD_DISABLE},
    {1, EC_DIR_INPUT, 0, NULL, EC_WD_DISABLE},
    {2, EC_DIR_OUTPUT, 1, slave_0_pdos + 0, EC_WD_DISABLE},
    {3, EC_DIR_INPUT, 1, slave_0_pdos + 1, EC_WD_DISABLE},
    {0xff}
};


//##################################################//
//##################################################//
//##################################################//
//##################################################//
//##################################################//

//This keeps the variables needed for the master
master_setup_variables_t master_setup={
		.nFirstRun=false,
		.master=NULL,
		.master_state={},
		.domain = 0,
		.domain_state = {},
		.domain_regs=domain_regs,
		.domain_pd=NULL,
};

//Slave Handles Array
ctrlproto_slv_handle slv_handles[]=
{
		//Slave 0
		{
			.out[0]=1,
			.out[1]=2,
			.__ecat_slave_in=&somanet_0_i_offset,
			.__ecat_slave_out=&somanet_0_o_offset,
			.__lost_packages_cnt=0,
			.__start=false,
			.__last_heartbeat_value=0,
			.is_responding=0,
			.slave_config=0,
			.slave_alias=0,
			.slave_pos=0,
			.slave_vendorid=0x000022d2,
			.slave_productid=0x00000201,
		}
};




#endif /* ETHERCAT_SETUP_H_ */
